// Code generated by schemar. DO NOT EDIT.

package geminiapi

import (
	"bytes"
	"context"
	"errors"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"

	json "github.com/go-json-experiment/json"
)

// Option is a functional option for configuring a Client.
type Option func(*Client)

// Client is the generated API client.
type Client struct {
	baseURL    string
	httpClient *http.Client
	userAgent  string
	apiKeys    map[string]string
	bearer     string
	editor     func(*http.Request) error
}

// WithUserAgent returns an Option that sets the User-Agent request header.
func WithUserAgent(s string) Option {
	return func(c *Client) { c.userAgent = s }
}

// WithAPIKey returns an Option that sets headerName to value on every request.
func WithAPIKey(headerName, value string) Option {
	return func(c *Client) {
		if c.apiKeys == nil {
			c.apiKeys = make(map[string]string)
		}
		c.apiKeys[headerName] = value
	}
}

// WithBearerToken returns an Option that sets the Authorization: Bearer header.
func WithBearerToken(s string) Option {
	return func(c *Client) { c.bearer = s }
}

// WithRequestEditor returns an Option that registers fn, called on every outgoing request
// after all other headers have been applied.
func WithRequestEditor(fn func(*http.Request) error) Option {
	return func(c *Client) { c.editor = fn }
}

// New constructs a Client targeting baseURL. If httpClient is nil, http.DefaultClient is
// used. baseURL must be non-empty or an error is returned.
func New(baseURL string, httpClient *http.Client, opts ...Option) (*Client, error) {
	if baseURL == "" {
		return nil, errors.New("baseURL must not be empty")
	}
	c := &Client{
		baseURL:    strings.TrimRight(baseURL, "/"),
		httpClient: httpClient,
	}
	if c.httpClient == nil {
		c.httpClient = http.DefaultClient
	}
	for _, o := range opts {
		o(c)
	}
	return c, nil
}

// do is the shared transport helper. It builds the full request URL, marshals
// body (when non-nil), sends the request, and unmarshals the JSON response into
// out (when non-nil). The raw *http.Response is returned; the body is consumed
// and closed before do returns when out is non-nil.
func (c *Client) do(ctx context.Context, method, path string, query url.Values, body any, out any) (*http.Response, error) {
	reqURL := c.baseURL + path
	if len(query) > 0 {
		reqURL += "?" + query.Encode()
	}

	var bodyReader io.Reader
	if body != nil {
		b, err := json.Marshal(body)
		if err != nil {
			return nil, fmt.Errorf("client: marshal body: %w", err)
		}
		bodyReader = bytes.NewReader(b)
	}

	req, err := http.NewRequestWithContext(ctx, method, reqURL, bodyReader)
	if err != nil {
		return nil, fmt.Errorf("client: new request: %w", err)
	}
	if body != nil {
		req.Header.Set("Content-Type", "application/json")
	}
	if out != nil {
		req.Header.Set("Accept", "application/json")
	}
	if c.userAgent != "" {
		req.Header.Set("User-Agent", c.userAgent)
	}
	if c.bearer != "" {
		req.Header.Set("Authorization", "Bearer "+c.bearer)
	}
	for hdr, val := range c.apiKeys {
		req.Header.Set(hdr, val)
	}
	if c.editor != nil {
		if err := c.editor(req); err != nil {
			return nil, fmt.Errorf("client: request editor: %w", err)
		}
	}

	resp, err := c.httpClient.Do(req)
	if err != nil {
		return nil, err
	}

	if resp.StatusCode >= 400 {
		return nil, decodeError(resp)
	}

	if out != nil {
		if err := json.UnmarshalRead(resp.Body, out); err != nil {
			resp.Body.Close()
			return nil, fmt.Errorf("client: unmarshal response: %w", err)
		}
		resp.Body.Close()
	}

	return resp, nil
}
