// Code generated by schemar. DO NOT EDIT.

package geminiapi

import (
	"context"
	"net/http"
	"net/url"
	"strings"
)

// Creating an interaction.
func (c *Client) CreateInteraction(ctx context.Context, apiVersion string, body *CreateInteractionBody) (*Interaction, error) {
	path := strings.NewReplacer(
		"{api_version}", url.PathEscape(apiVersion),
	).Replace("/{api_version}/interactions")
	var out Interaction
	if _, err := c.do(ctx, "POST", path, nil, body, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

// Retrieving an interaction.
func (c *Client) GetInteractionById(ctx context.Context, id string, apiVersion string, params *GetInteractionByIdParams) (*Interaction, error) {
	path := strings.NewReplacer(
		"{id}", url.PathEscape(id),
		"{api_version}", url.PathEscape(apiVersion),
	).Replace("/{api_version}/interactions/{id}")
	var query url.Values
	if params != nil {
		query = params.encode()
	}
	var out Interaction
	if _, err := c.do(ctx, "GET", path, query, nil, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

// Deleting an interaction.
func (c *Client) DeleteInteraction(ctx context.Context, id string, apiVersion string) (*DeleteInteractionResponse, error) {
	path := strings.NewReplacer(
		"{id}", url.PathEscape(id),
		"{api_version}", url.PathEscape(apiVersion),
	).Replace("/{api_version}/interactions/{id}")
	var out DeleteInteractionResponse
	if _, err := c.do(ctx, "DELETE", path, nil, nil, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

// Canceling an interaction.
func (c *Client) CancelInteractionById(ctx context.Context, id string, apiVersion string) (*Interaction, error) {
	path := strings.NewReplacer(
		"{id}", url.PathEscape(id),
		"{api_version}", url.PathEscape(apiVersion),
	).Replace("/{api_version}/interactions/{id}/cancel")
	var out Interaction
	if _, err := c.do(ctx, "POST", path, nil, nil, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

// ListWebhooks calls GET /{api_version}/webhooks.
func (c *Client) ListWebhooks(ctx context.Context, apiVersion string, params *ListWebhooksParams) (*http.Response, error) {
	path := strings.NewReplacer(
		"{api_version}", url.PathEscape(apiVersion),
	).Replace("/{api_version}/webhooks")
	var query url.Values
	if params != nil {
		query = params.encode()
	}
	return c.do(ctx, "GET", path, query, nil, nil)
}

// CreateWebhook calls POST /{api_version}/webhooks.
func (c *Client) CreateWebhook(ctx context.Context, apiVersion string, body *Webhook) (*http.Response, error) {
	path := strings.NewReplacer(
		"{api_version}", url.PathEscape(apiVersion),
	).Replace("/{api_version}/webhooks")
	return c.do(ctx, "POST", path, nil, body, nil)
}

// ListAgents calls GET /{api_version}/agents.
func (c *Client) ListAgents(ctx context.Context, apiVersion string, params *ListAgentsParams) (*http.Response, error) {
	path := strings.NewReplacer(
		"{api_version}", url.PathEscape(apiVersion),
	).Replace("/{api_version}/agents")
	var query url.Values
	if params != nil {
		query = params.encode()
	}
	return c.do(ctx, "GET", path, query, nil, nil)
}

// CreateAgent calls POST /{api_version}/agents.
func (c *Client) CreateAgent(ctx context.Context, apiVersion string, body *Agent) (*http.Response, error) {
	path := strings.NewReplacer(
		"{api_version}", url.PathEscape(apiVersion),
	).Replace("/{api_version}/agents")
	return c.do(ctx, "POST", path, nil, body, nil)
}

// GetAgent calls GET /{api_version}/agents/{id}.
func (c *Client) GetAgent(ctx context.Context, apiVersion string, id string) (*http.Response, error) {
	path := strings.NewReplacer(
		"{api_version}", url.PathEscape(apiVersion),
		"{id}", url.PathEscape(id),
	).Replace("/{api_version}/agents/{id}")
	return c.do(ctx, "GET", path, nil, nil, nil)
}

// DeleteAgent calls DELETE /{api_version}/agents/{id}.
func (c *Client) DeleteAgent(ctx context.Context, apiVersion string, id string) (*http.Response, error) {
	path := strings.NewReplacer(
		"{api_version}", url.PathEscape(apiVersion),
		"{id}", url.PathEscape(id),
	).Replace("/{api_version}/agents/{id}")
	return c.do(ctx, "DELETE", path, nil, nil, nil)
}

// GetWebhook calls GET /{api_version}/webhooks/{id}.
func (c *Client) GetWebhook(ctx context.Context, apiVersion string, id string) (*http.Response, error) {
	path := strings.NewReplacer(
		"{api_version}", url.PathEscape(apiVersion),
		"{id}", url.PathEscape(id),
	).Replace("/{api_version}/webhooks/{id}")
	return c.do(ctx, "GET", path, nil, nil, nil)
}

// UpdateWebhook calls PATCH /{api_version}/webhooks/{id}.
func (c *Client) UpdateWebhook(ctx context.Context, apiVersion string, id string, params *UpdateWebhookParams, body *WebhookUpdate) (*http.Response, error) {
	path := strings.NewReplacer(
		"{api_version}", url.PathEscape(apiVersion),
		"{id}", url.PathEscape(id),
	).Replace("/{api_version}/webhooks/{id}")
	var query url.Values
	if params != nil {
		query = params.encode()
	}
	return c.do(ctx, "PATCH", path, query, body, nil)
}

// DeleteWebhook calls DELETE /{api_version}/webhooks/{id}.
func (c *Client) DeleteWebhook(ctx context.Context, apiVersion string, id string) (*http.Response, error) {
	path := strings.NewReplacer(
		"{api_version}", url.PathEscape(apiVersion),
		"{id}", url.PathEscape(id),
	).Replace("/{api_version}/webhooks/{id}")
	return c.do(ctx, "DELETE", path, nil, nil, nil)
}

// RotateSigningSecret calls POST /{api_version}/webhooks/{id}:rotateSigningSecret.
func (c *Client) RotateSigningSecret(ctx context.Context, apiVersion string, id string, body *RotateSigningSecretRequest) (*http.Response, error) {
	path := strings.NewReplacer(
		"{api_version}", url.PathEscape(apiVersion),
		"{id}", url.PathEscape(id),
	).Replace("/{api_version}/webhooks/{id}:rotateSigningSecret")
	return c.do(ctx, "POST", path, nil, body, nil)
}

// PingWebhook calls POST /{api_version}/webhooks/{id}:ping.
func (c *Client) PingWebhook(ctx context.Context, apiVersion string, id string, body *PingWebhookRequest) (*http.Response, error) {
	path := strings.NewReplacer(
		"{api_version}", url.PathEscape(apiVersion),
		"{id}", url.PathEscape(id),
	).Replace("/{api_version}/webhooks/{id}:ping")
	return c.do(ctx, "POST", path, nil, body, nil)
}
