// Code generated by schemar. DO NOT EDIT.

package geminiapi

import (
	"net/http"
	"net/url"
	"strconv"
)

// GetInteractionByIdParams holds query and header parameters for the GetInteractionById operation.
type GetInteractionByIdParams struct {
	Stream       *bool  `form:"stream"`
	LastEventID  string `form:"last_event_id"`
	IncludeInput *bool  `form:"include_input"`
}

// encode converts the query parameters in p to URL query values.
func (p *GetInteractionByIdParams) encode() url.Values {
	q := url.Values{}
	if p.Stream != nil {
		q.Set("stream", strconv.FormatBool(*p.Stream))
	}
	if p.LastEventID != "" {
		q.Set("last_event_id", p.LastEventID)
	}
	if p.IncludeInput != nil {
		q.Set("include_input", strconv.FormatBool(*p.IncludeInput))
	}
	return q
}

// encodeHeaders converts the header parameters in p to HTTP request headers.
func (p *GetInteractionByIdParams) encodeHeaders() http.Header {
	h := http.Header{}
	return h
}

// ListWebhooksParams holds query and header parameters for the ListWebhooks operation.
type ListWebhooksParams struct {
	PageSize  *int32 `form:"page_size"`
	PageToken string `form:"page_token"`
}

// encode converts the query parameters in p to URL query values.
func (p *ListWebhooksParams) encode() url.Values {
	q := url.Values{}
	if p.PageSize != nil {
		q.Set("page_size", strconv.FormatInt(int64(*p.PageSize), 10))
	}
	if p.PageToken != "" {
		q.Set("page_token", p.PageToken)
	}
	return q
}

// encodeHeaders converts the header parameters in p to HTTP request headers.
func (p *ListWebhooksParams) encodeHeaders() http.Header {
	h := http.Header{}
	return h
}

// ListAgentsParams holds query and header parameters for the ListAgents operation.
type ListAgentsParams struct {
	Parent    string `form:"parent"`
	PageSize  *int32 `form:"pageSize"`
	PageToken string `form:"pageToken"`
}

// encode converts the query parameters in p to URL query values.
func (p *ListAgentsParams) encode() url.Values {
	q := url.Values{}
	if p.Parent != "" {
		q.Set("parent", p.Parent)
	}
	if p.PageSize != nil {
		q.Set("pageSize", strconv.FormatInt(int64(*p.PageSize), 10))
	}
	if p.PageToken != "" {
		q.Set("pageToken", p.PageToken)
	}
	return q
}

// encodeHeaders converts the header parameters in p to HTTP request headers.
func (p *ListAgentsParams) encodeHeaders() http.Header {
	h := http.Header{}
	return h
}

// UpdateWebhookParams holds query and header parameters for the UpdateWebhook operation.
type UpdateWebhookParams struct {
	UpdateMask string `form:"update_mask"`
}

// encode converts the query parameters in p to URL query values.
func (p *UpdateWebhookParams) encode() url.Values {
	q := url.Values{}
	if p.UpdateMask != "" {
		q.Set("update_mask", p.UpdateMask)
	}
	return q
}

// encodeHeaders converts the header parameters in p to HTTP request headers.
func (p *UpdateWebhookParams) encodeHeaders() http.Header {
	h := http.Header{}
	return h
}
