// Copyright 2026 The schemar Authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Package oneof provides classification and runtime helpers for oneOf/anyOf
// union types generated by schemar.
//
// The package is imported by emit (the code generator), not by the
// generated code itself.  It must remain free of libopenapi imports and
// operates exclusively on its own IR-level types.
//
// Generated union types follow Strategy B (§5 of the design plan): a wrapper
// struct holds one pointer field per variant and retains the raw
// jsontext.Value when no variant can be decoded.  Strategy A (any fallback)
// is emitted only when a union contains at least one primitive variant
// (string / integer / number / boolean / null), because those types cannot
// be represented cleanly by a pointer-per-variant wrapper.
package oneof

import (
	"errors"

	json "github.com/go-json-experiment/json"
	"github.com/go-json-experiment/json/jsontext"
)

// ── Classification types ──────────────────────────────────────────────────

// UnionVariant describes one member of a oneOf/anyOf union as seen by the IR
// builder.
type UnionVariant struct {
	// TypeName is the Go type name of this variant (e.g. "CreateModelInteractionParams").
	// Empty for primitive variants.
	TypeName string

	// IsRef is true when the variant is a $ref to a named schema rather than
	// an inline type.
	IsRef bool

	// IsPrimitive is true for JSON-Schema primitive types (string, integer,
	// number, boolean, null). Any primitive variant forces StrategyA.
	IsPrimitive bool

	// JSONType is the raw JSON-Schema type string ("string", "integer", …)
	// and is set only when IsPrimitive is true.
	JSONType string

	// DiscriminatorValue is the value of the discriminator property that
	// identifies this variant (e.g. "model", "agent"). Empty when the OpenAPI
	// spec does not declare a discriminator or does not map this variant.
	DiscriminatorValue string
}

// Strategy selects how a union type is encoded in generated Go code.
type Strategy int

const (
	// StrategyB is the default: a wrapper struct with one *T per ref variant
	// plus a retained raw jsontext.Value fallback.
	StrategyB Strategy = iota

	// StrategyA is the fallback for unions that contain at least one primitive
	// variant. The union collapses to a single any field with a diagnostic
	// comment. See StrategyADiagnostic.
	StrategyA
)

// UnionInfo is the result of Classify; it summarises a oneOf/anyOf union and
// the chosen encoding strategy.
type UnionInfo struct {
	// IsOneOf is true for oneOf; false for anyOf. The emitted struct is
	// identical — anyOf allows multiple non-nil variant fields simultaneously,
	// which is documented in the generated godoc.
	IsOneOf bool

	// Variants are the member types of this union in declaration order.
	Variants []UnionVariant

	// Discriminator is the name of the JSON property used to distinguish
	// variants (from OpenAPI discriminator.propertyName). Empty when absent.
	Discriminator string

	// Strategy is the chosen encoding strategy.
	Strategy Strategy
}

// StrategyADiagnostic is the comment emitted immediately above the any field
// of a Strategy A union to alert consumers about the type-unsafe fallback.
const StrategyADiagnostic = "// FIXME: oneOf with primitives — type-safe Strategy B unavailable; using any."

// Classify analyses the variants of a oneOf/anyOf schema and returns the
// UnionInfo that captures the chosen strategy. Any primitive variant in the
// list forces StrategyA for the whole union.
func Classify(isOneOf bool, discriminator string, variants []UnionVariant) UnionInfo {
	strategy := StrategyB
	for _, v := range variants {
		if v.IsPrimitive {
			strategy = StrategyA
			break
		}
	}
	return UnionInfo{
		IsOneOf:       isOneOf,
		Variants:      variants,
		Discriminator: discriminator,
		Strategy:      strategy,
	}
}

// ── Runtime helpers ───────────────────────────────────────────────────────
//
// These helpers implement the marshal/unmarshal logic that the emitter inlines
// into generated Strategy B wrapper types.  They are provided as callable
// functions so that the unit tests can exercise the exact same logic without
// requiring a full code-generation round-trip.

// ErrNoVariantMatched is returned by MatchDiscriminator when the discriminator
// field is present in the JSON object but its value does not correspond to any
// known variant. The caller should retain the raw bytes.
var ErrNoVariantMatched = errors.New("oneof: discriminator value did not match any known variant")

// MatchDiscriminator reads the value of field from a JSON object in data and
// returns the index into values whose string equals that value.
//
// Return values:
//
//   - idx ≥ 0, nil  — field was found and its value matched values[idx].
//   - -1, nil       — field is absent from the object; caller should fall back
//     to trial-decode or retain raw.
//   - -1, err       — data is not a valid JSON object or the field value is not
//     a string.
//
// ErrNoVariantMatched is returned when the field is present but its value does
// not appear in values; the caller may still choose to retain raw bytes.
func MatchDiscriminator(data []byte, field string, values []string) (int, error) {
	var obj map[string]jsontext.Value
	if err := json.Unmarshal(data, &obj); err != nil {
		return -1, err
	}

	raw, ok := obj[field]
	if !ok {
		return -1, nil // discriminator field absent; not an error
	}

	var s string
	if err := json.Unmarshal([]byte(raw), &s); err != nil {
		return -1, err
	}

	for i, v := range values {
		if v == s {
			return i, nil
		}
	}

	return -1, ErrNoVariantMatched
}

// UnmarshalTrial attempts to unmarshal data into each of the supplied
// decoders in order and returns the index of the first decoder that succeeds
// without error, along with the successfully decoded value. The decoders
// should apply strict unmarshaling (e.g. RejectUnknownMembers) so that
// structurally incompatible variants are rejected quickly.
//
// -1 is returned when every decoder fails. The caller must retain raw bytes.
func UnmarshalTrial(data []byte, decoders []func([]byte) error) (int, error) {
	for i, dec := range decoders {
		if err := dec(data); err == nil {
			return i, nil
		}
	}
	return -1, nil
}

// StrictUnmarshal unmarshals data into v using RejectUnknownMembers so that
// structurally incompatible JSON objects are rejected. It is the recommended
// decoder function to supply to UnmarshalTrial for Strategy B trial-decode.
func StrictUnmarshal(data []byte, v any) error {
	return json.Unmarshal(data, v, json.RejectUnknownMembers(true))
}
