// Copyright 2026 The schemar Authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package emit

import (
	_ "embed"
	"fmt"
	"go/format"
	"slices"
	"strings"
	"text/template"
	"unicode"

	"github.com/zchee/schemar/ir"
)

//go:embed templates/client.tmpl
var clientTmplSrc string

//go:embed templates/methods.tmpl
var methodsTmplSrc string

// Client generates the content of client.go for the given package name.
// The output is fully static (the Client struct, Option constructors, New,
// and the do transport helper). [go/format.Source] is applied before returning.
func Client(pkgName string) ([]byte, error) {
	return renderStaticTemplate("client", clientTmplSrc, pkgName)
}

// renderStaticTemplate parses and executes a fully-static emit template whose
// only datum is the package name, then runs [go/format.Source] over the
// result. On format failure the unformatted source is returned alongside the
// error so callers can write a .broken file for debugging.
func renderStaticTemplate(label, tmplSrc, pkgName string) ([]byte, error) {
	tmpl, err := template.New(label).Parse(tmplSrc)
	if err != nil {
		return nil, fmt.Errorf("emit/%s: parse template: %w", label, err)
	}

	data := struct{ PackageName string }{PackageName: pkgName}

	var sb strings.Builder
	if err := tmpl.Execute(&sb, data); err != nil {
		return nil, fmt.Errorf("emit/%s: execute template: %w", label, err)
	}

	formatted, fmtErr := format.Source([]byte(sb.String()))
	if fmtErr != nil {
		return []byte(sb.String()), fmt.Errorf("emit/%s: go/format: %w", label, fmtErr)
	}
	return formatted, nil
}

// methodsData is the top-level value passed to the methods template.
type methodsData struct {
	// PackageName is the Go package declaration name.
	PackageName string
	// Imports is the sorted, formatted list of import lines.
	Imports []string
	// Operations is the ordered list of operations to emit.
	Operations []ir.Operation
}

// Methods generates the content of methods.go (one method per ir.Operation).
// [go/format.Source] is applied; on failure the raw output is returned
// alongside the error so callers can write a .broken file for debugging.
func Methods(irResult *ir.IR, pkgName string) ([]byte, error) {
	if len(irResult.Operations) == 0 {
		src := "// Code generated by schemar. DO NOT EDIT.\n\npackage " + pkgName + "\n"
		return []byte(src), nil
	}

	funcs := template.FuncMap{
		"methodDecl": renderMethodDecl,
	}

	tmpl, err := template.New("methods").Funcs(funcs).Parse(methodsTmplSrc)
	if err != nil {
		return nil, fmt.Errorf("emit/methods: parse template: %w", err)
	}

	data := methodsData{
		PackageName: pkgName,
		Imports:     computeMethodImports(irResult.Operations),
		Operations:  irResult.Operations,
	}

	var sb strings.Builder
	if err := tmpl.Execute(&sb, data); err != nil {
		return nil, fmt.Errorf("emit/methods: execute template: %w", err)
	}

	formatted, fmtErr := format.Source([]byte(sb.String()))
	if fmtErr != nil {
		return []byte(sb.String()), fmt.Errorf("emit/methods: go/format: %w", fmtErr)
	}
	return formatted, nil
}

// ── Import computation ──────────────────────────────────────────────────────

// computeMethodImports returns the sorted import declaration lines needed
// for the generated methods.go file. Only packages actually referenced by the
// generated method bodies are included.
func computeMethodImports(ops []ir.Operation) []string {
	paths := map[string]string{
		"context": "",
	}

	for _, op := range ops {
		if len(op.PathParams) > 0 {
			paths["net/url"] = ""
			paths["strings"] = ""
		}
		if len(op.QueryParams) > 0 {
			paths["net/url"] = ""
		}
		if primaryResponseType(op.Responses) == nil {
			// Returns (*http.Response, error)
			paths["net/http"] = ""
		}
	}

	var stdlib, thirdparty []string
	for p := range paths {
		if strings.Contains(p, ".") {
			thirdparty = append(thirdparty, p)
		} else {
			stdlib = append(stdlib, p)
		}
	}
	slices.Sort(stdlib)
	slices.Sort(thirdparty)

	result := make([]string, 0, len(paths))
	for _, p := range stdlib {
		result = append(result, formatImport(p, paths[p]))
	}
	for _, p := range thirdparty {
		result = append(result, formatImport(p, paths[p]))
	}
	return result
}

// ── Response type selection ─────────────────────────────────────────────────

// primaryResponseType returns the TypeRef for the lowest 2xx response code,
// or nil when no 2xx response has a JSON body (the method returns *http.Response).
func primaryResponseType(responses map[int]*ir.TypeRef) *ir.TypeRef {
	var codes []int
	for code := range responses {
		if code >= 200 && code < 300 {
			codes = append(codes, code)
		}
	}
	if len(codes) == 0 {
		return nil
	}
	slices.Sort(codes)
	return responses[codes[0]]
}

// returnedByValue reports whether a response of type t is returned by value
// rather than by pointer. Slice and map types are returned directly; all other
// named types are returned as a pointer. The IsSlice and IsMap flags are set by
// the IR builder, so named aliases to slices or maps (e.g. type MySlice []T)
// are recognized as well, not only inline "[]" or "map[" type expressions.
func returnedByValue(t *ir.TypeRef) bool {
	if t == nil {
		return false
	}
	return t.IsSlice || t.IsMap
}

// ── Method declaration rendering ────────────────────────────────────────────

// renderMethodDecl generates the full Go source for one API operation method.
// It is registered as a FuncMap entry so the methods template can call it.
func renderMethodDecl(op ir.Operation) (string, error) {
	var b strings.Builder

	respType := primaryResponseType(op.Responses)
	hasQueryParams := len(op.QueryParams) > 0
	hasPathParams := len(op.PathParams) > 0

	// Godoc comment.
	if op.DocComment != "" {
		writeComment(&b, op.DocComment, "")
	}

	// Function signature: (c *Client) GoName(ctx, [pathParams], [params], [body]) (ReturnType, error)
	fmt.Fprintf(&b, "func (c *Client) %s(ctx context.Context", op.GoName)

	for _, p := range op.PathParams {
		fmt.Fprintf(&b, ", %s string", paramVarName(p.GoName))
	}

	if hasQueryParams {
		fmt.Fprintf(&b, ", params *%sParams", op.GoName)
	}

	if op.RequestBody != nil {
		fmt.Fprintf(&b, ", body *%s", op.RequestBody.Name)
	}

	// A slice or map response is returned by value; all other named types are
	// returned by pointer.
	respByValue := returnedByValue(respType)

	switch {
	case respType == nil:
		fmt.Fprint(&b, ") (*http.Response, error) {\n")
	case respByValue:
		fmt.Fprintf(&b, ") (%s, error) {\n", respType.Name)
	default:
		fmt.Fprintf(&b, ") (*%s, error) {\n", respType.Name)
	}

	// Path construction.
	if hasPathParams {
		fmt.Fprint(&b, "\tpath := strings.NewReplacer(\n")
		for _, p := range op.PathParams {
			fmt.Fprintf(&b, "\t\t%q, url.PathEscape(%s),\n", "{"+p.Name+"}", paramVarName(p.GoName))
		}
		fmt.Fprintf(&b, "\t).Replace(%q)\n", op.Path)
	} else {
		fmt.Fprintf(&b, "\tpath := %q\n", op.Path)
	}

	// Query construction.
	if hasQueryParams {
		fmt.Fprint(&b, "\tvar query url.Values\n")
		fmt.Fprint(&b, "\tif params != nil {\n")
		fmt.Fprint(&b, "\t\tquery = params.encode()\n")
		fmt.Fprint(&b, "\t}\n")
	}

	// Determine argument expressions for c.do.
	queryArg := "nil"
	if hasQueryParams {
		queryArg = "query"
	}
	bodyArg := "nil"
	if op.RequestBody != nil {
		bodyArg = "body"
	}

	// do call and return.
	if respType == nil {
		fmt.Fprintf(&b, "\treturn c.do(ctx, %q, path, %s, %s, nil)\n", op.Method, queryArg, bodyArg)
	} else {
		fmt.Fprintf(&b, "\tvar out %s\n", respType.Name)
		fmt.Fprintf(&b, "\tif _, err := c.do(ctx, %q, path, %s, %s, &out); err != nil {\n", op.Method, queryArg, bodyArg)
		fmt.Fprint(&b, "\t\treturn nil, err\n")
		fmt.Fprint(&b, "\t}\n")
		if respByValue {
			fmt.Fprint(&b, "\treturn out, nil\n")
		} else {
			fmt.Fprint(&b, "\treturn &out, nil\n")
		}
	}

	fmt.Fprint(&b, "}\n")

	return b.String(), nil
}

// ── Naming helpers ─────────────────────────────────────────────────────────

// paramVarName converts a PascalCase IR GoName into a valid camelCase local
// variable name for use in function signatures and local assignments.
//
// Conversion rules:
//   - Single uppercase + lowercase tail ("Name"): lowercase first rune → "name"
//   - All-uppercase acronym ("ID", "URL"): fully lowercase → "id", "url"
//   - Initialism prefix + PascalCase suffix ("APIVersion", "HTTPClient"):
//     lowercase the initialism prefix, keep the following word as-is → "apiVersion", "httpClient"
func paramVarName(goName string) string {
	if goName == "" {
		return "_"
	}
	runes := []rune(goName)

	// Find the index of the first lowercase rune.
	i := 0
	for i < len(runes) && unicode.IsUpper(runes[i]) {
		i++
	}

	switch {
	case i == len(runes):
		// All uppercase ("ID", "URL") → fully lowercase.
		return strings.ToLower(goName)
	case i <= 1:
		// First rune uppercase, second is lowercase ("Name") → lowercase first rune only.
		runes[0] = unicode.ToLower(runes[0])
		return string(runes)
	default:
		// Multiple uppercase prefix ("API" in "APIVersion") → lowercase the initialism
		// (all but the last uppercase rune, which starts the next PascalCase word).
		for j := range i - 1 {
			runes[j] = unicode.ToLower(runes[j])
		}
		return string(runes)
	}
}
