// Copyright 2026 The schemar Authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Package emit contains emitters that convert a schemar IR into Go source files
// using text/template and go/format.
package emit

import (
	_ "embed"
	"fmt"
	"go/format"
	"strings"
	"text/template"

	"github.com/zchee/schemar/ir"
)

//go:embed templates/params.tmpl
var paramsTmplSrc string

// paramsData is the top-level data structure passed to the params template.
type paramsData struct {
	// Package is the Go package declaration name.
	Package string
	// NeedsStrconv is true when at least one field requires the strconv import.
	NeedsStrconv bool
	// NeedsTime is true when at least one field requires the time import.
	NeedsTime bool
	// Structs is the ordered list of Params structs to emit.
	Structs []paramsStructData
}

// paramsStructData describes one generated <Op>Params struct.
type paramsStructData struct {
	// Name is the exported Go type name (e.g. "ListInteractionsParams").
	Name string
	// OpGoName is the operation's GoName used in the godoc comment.
	OpGoName string
	// Fields is the ordered list of query + header parameter fields.
	Fields []paramFieldData
	// QueryEncodeBlocks contains the encode() method body lines for query params.
	QueryEncodeBlocks []string
	// HeaderEncodeBlocks contains the encodeHeaders() method body lines for header params.
	HeaderEncodeBlocks []string
}

// paramFieldData describes one field in a Params struct.
type paramFieldData struct {
	// GoName is the exported Go field name.
	GoName string
	// GoType is the Go type expression (without pointer prefix).
	GoType string
	// IsPointer indicates the field is wrapped in a pointer.
	IsPointer bool
	// IsEnum is true when the named type is a KindEnum. The params emitter uses
	// this to decide whether string(x) is a valid cast in encode().
	IsEnum bool
	// StructTag is the complete struct tag string, e.g. `form:"name"`.
	StructTag string
	// DocComment is the optional field-level godoc text.
	DocComment string
}

// Params generates the params.go source for all operations in irResult that
// have at least one query or header parameter. The generated file uses
// go/format for consistent formatting.
//
// Struct tags use `form:"<name>"` for query parameters and `header:"<name>"`
// for header parameters. A separate `encodeHeaders() http.Header` method
// handles header-only encoding; `encode() url.Values` handles query params.
//
// If go/format.Source fails the unformatted source is returned alongside the
// error so the caller can write a .broken file for debugging.
func Params(irResult *ir.IR, pkgName string) ([]byte, error) {
	tmpl, err := template.New("params").Parse(paramsTmplSrc)
	if err != nil {
		return nil, fmt.Errorf("emit/params: parse template: %w", err)
	}

	data := buildParamsData(irResult, pkgName)
	if len(data.Structs) == 0 {
		src := "// Code generated by schemar. DO NOT EDIT.\n\npackage " + pkgName + "\n"
		return []byte(src), nil
	}

	var sb strings.Builder
	if err := tmpl.Execute(&sb, data); err != nil {
		return nil, fmt.Errorf("emit/params: execute template: %w", err)
	}
	raw := []byte(sb.String())

	formatted, fmtErr := format.Source(raw)
	if fmtErr != nil {
		return raw, fmt.Errorf("emit/params: go/format: %w", fmtErr)
	}
	return formatted, nil
}

// buildParamsData converts the IR into the template data structure.
func buildParamsData(irResult *ir.IR, pkgName string) paramsData {
	data := paramsData{Package: pkgName}

	for _, op := range irResult.Operations {
		hasQuery := len(op.QueryParams) > 0
		hasHeader := len(op.HeaderParams) > 0
		if !hasQuery && !hasHeader {
			continue
		}

		structData := paramsStructData{
			Name:     op.GoName + "Params",
			OpGoName: op.GoName,
		}

		// Query params → form tag + encode() body.
		for _, param := range op.QueryParams {
			fd := paramFieldData{
				GoName:     param.GoName,
				GoType:     param.GoType.Name,
				IsPointer:  param.IsPointer,
				IsEnum:     param.GoType.IsEnum,
				StructTag:  `form:"` + param.Name + `"`,
				DocComment: param.DocComment,
			}
			block := computeEncodeBlock(fd.GoName, fd.GoType, param.Name, fd.IsPointer, fd.IsEnum, false)
			if block != "" {
				structData.Fields = append(structData.Fields, fd)
				structData.QueryEncodeBlocks = append(structData.QueryEncodeBlocks, block)
				if needsStrconv(fd.GoType) {
					data.NeedsStrconv = true
				}
				if strings.Contains(fd.GoType, "time.Time") {
					data.NeedsTime = true
				}
			}
		}

		// Header params → header tag + encodeHeaders() body.
		for _, param := range op.HeaderParams {
			fd := paramFieldData{
				GoName:     param.GoName,
				GoType:     param.GoType.Name,
				IsPointer:  param.IsPointer,
				IsEnum:     param.GoType.IsEnum,
				StructTag:  `header:"` + param.Name + `"`,
				DocComment: param.DocComment,
			}
			block := computeEncodeBlock(fd.GoName, fd.GoType, param.Name, fd.IsPointer, fd.IsEnum, true)
			if block != "" {
				structData.Fields = append(structData.Fields, fd)
				structData.HeaderEncodeBlocks = append(structData.HeaderEncodeBlocks, block)
			}
		}

		data.Structs = append(data.Structs, structData)
	}
	return data
}

// computeEncodeBlock produces the Go code fragment for encoding one field.
// isEnum indicates the named type is a string enum (string cast is valid).
// isHeader selects between h.Set (header) and q.Set (query) calls.
// Generated code uses no reflect — only direct field access and strconv/time.
// Returns an empty string for types that cannot be safely serialised to a URL
// query string (maps, objects, anonymous structs); callers must skip such fields.
func computeEncodeBlock(goName, goType, paramName string, isPointer, isEnum, isHeader bool) string {
	varExpr := "p." + goName
	setter := "q"
	if isHeader {
		setter = "h"
	}

	// map[...] → not URL-serialisable; skip.
	if strings.HasPrefix(goType, "map[") {
		return ""
	}

	// Slice → repeated Add calls.
	if strings.HasPrefix(goType, "[]") {
		elemType := strings.TrimPrefix(goType, "[]")
		if elemType == "byte" {
			return fmt.Sprintf("\tif len(%s) > 0 {\n\t\t%s.Set(%q, string(%s))\n\t}",
				varExpr, setter, paramName, varExpr)
		}
		// Slice elements are assumed non-enum scalars; isEnum applies to the param type, not the element.
		elemEncode := scalarEncodeExpr(elemType, "v", false)
		if elemEncode == "" {
			return "" // element type not serialisable
		}
		return fmt.Sprintf("\tfor _, v := range %s {\n\t\t%s.Add(%q, %s)\n\t}",
			varExpr, setter, paramName, elemEncode)
	}

	// Pointer wrapper → nil guard.
	if isPointer {
		deref := "*" + varExpr
		valueExpr := scalarEncodeExpr(goType, deref, isEnum)
		if valueExpr == "" {
			return "" // pointed-to type not serialisable
		}
		return fmt.Sprintf("\tif %s != nil {\n\t\t%s.Set(%q, %s)\n\t}",
			varExpr, setter, paramName, valueExpr)
	}

	// Non-pointer string: skip zero value.
	if goType == "string" {
		return fmt.Sprintf("\tif %s != \"\" {\n\t\t%s.Set(%q, %s)\n\t}",
			varExpr, setter, paramName, varExpr)
	}

	// Non-pointer non-nilable: always encode.
	expr := scalarEncodeExpr(goType, varExpr, isEnum)
	if expr == "" {
		return "" // type not serialisable
	}
	return fmt.Sprintf("\t%s.Set(%q, %s)", setter, paramName, expr)
}

// scalarEncodeExpr returns the Go expression that converts expr (of goType) to
// a string for use in URL query values or HTTP headers.
// isEnum must be true for named types that are KindEnum; for those, string(x)
// is a valid cast. For all other non-primitive named types (structs, maps) the
// function returns an empty string to signal "skip field".
func scalarEncodeExpr(goType, expr string, isEnum bool) string {
	switch goType {
	case "string":
		return expr
	case "bool":
		return "strconv.FormatBool(" + expr + ")"
	case "int64":
		return "strconv.FormatInt(" + expr + ", 10)"
	case "int32":
		return "strconv.FormatInt(int64(" + expr + "), 10)"
	case "float64":
		return "strconv.FormatFloat(" + expr + ", 'g', -1, 64)"
	case "float32":
		return "strconv.FormatFloat(float64(" + expr + "), 'g', -1, 32)"
	case "time.Time":
		return expr + ".Format(time.RFC3339)"
	case "any", "[]byte":
		return "" // not serialisable as a simple query string value
	default:
		// Named type: only string-cast when the caller confirmed it is a
		// KindEnum (string-based alias with exported const values).
		if isEnum {
			return "string(" + expr + ")"
		}
		return "" // struct, map, or other non-encodeable named type — skip
	}
}

// needsStrconv reports whether the given Go type requires a strconv import.
func needsStrconv(goType string) bool {
	switch goType {
	case "bool", "int32", "int64", "float32", "float64":
		return true
	}
	if strings.HasPrefix(goType, "[]") {
		return needsStrconv(strings.TrimPrefix(goType, "[]"))
	}
	return false
}
