// Code generated by schemar. DO NOT EDIT.

package openaiapi

import (
	"net/http"
	"net/url"
	"strconv"
)

// ListAssistantsParams holds query and header parameters for the ListAssistants operation.
type ListAssistantsParams struct {
	Limit  *int64                    `form:"limit"`
	Order  ListAssistantsParamsOrder `form:"order"`
	After  string                    `form:"after"`
	Before string                    `form:"before"`
}

// encode converts the query parameters in p to URL query values.
func (p *ListAssistantsParams) encode() url.Values {
	q := url.Values{}
	if p.Limit != nil {
		q.Set("limit", strconv.FormatInt(*p.Limit, 10))
	}
	q.Set("order", string(p.Order))
	if p.After != "" {
		q.Set("after", p.After)
	}
	if p.Before != "" {
		q.Set("before", p.Before)
	}
	return q
}

// encodeHeaders converts the header parameters in p to HTTP request headers.
func (p *ListAssistantsParams) encodeHeaders() http.Header {
	h := http.Header{}
	return h
}

// ListVoiceConsentsParams holds query and header parameters for the ListVoiceConsents operation.
type ListVoiceConsentsParams struct {
	After string `form:"after"`
	Limit *int64 `form:"limit"`
}

// encode converts the query parameters in p to URL query values.
func (p *ListVoiceConsentsParams) encode() url.Values {
	q := url.Values{}
	if p.After != "" {
		q.Set("after", p.After)
	}
	if p.Limit != nil {
		q.Set("limit", strconv.FormatInt(*p.Limit, 10))
	}
	return q
}

// encodeHeaders converts the header parameters in p to HTTP request headers.
func (p *ListVoiceConsentsParams) encodeHeaders() http.Header {
	h := http.Header{}
	return h
}

// ListBatchesParams holds query and header parameters for the ListBatches operation.
type ListBatchesParams struct {
	After string `form:"after"`
	Limit *int64 `form:"limit"`
}

// encode converts the query parameters in p to URL query values.
func (p *ListBatchesParams) encode() url.Values {
	q := url.Values{}
	if p.After != "" {
		q.Set("after", p.After)
	}
	if p.Limit != nil {
		q.Set("limit", strconv.FormatInt(*p.Limit, 10))
	}
	return q
}

// encodeHeaders converts the header parameters in p to HTTP request headers.
func (p *ListBatchesParams) encodeHeaders() http.Header {
	h := http.Header{}
	return h
}

// ListChatCompletionsParams holds query and header parameters for the ListChatCompletions operation.
type ListChatCompletionsParams struct {
	Model string                         `form:"model"`
	After string                         `form:"after"`
	Limit *int64                         `form:"limit"`
	Order ListChatCompletionsParamsOrder `form:"order"`
}

// encode converts the query parameters in p to URL query values.
func (p *ListChatCompletionsParams) encode() url.Values {
	q := url.Values{}
	if p.Model != "" {
		q.Set("model", p.Model)
	}
	if p.After != "" {
		q.Set("after", p.After)
	}
	if p.Limit != nil {
		q.Set("limit", strconv.FormatInt(*p.Limit, 10))
	}
	q.Set("order", string(p.Order))
	return q
}

// encodeHeaders converts the header parameters in p to HTTP request headers.
func (p *ListChatCompletionsParams) encodeHeaders() http.Header {
	h := http.Header{}
	return h
}

// GetChatCompletionMessagesParams holds query and header parameters for the GetChatCompletionMessages operation.
type GetChatCompletionMessagesParams struct {
	After string                               `form:"after"`
	Limit *int64                               `form:"limit"`
	Order GetChatCompletionMessagesParamsOrder `form:"order"`
}

// encode converts the query parameters in p to URL query values.
func (p *GetChatCompletionMessagesParams) encode() url.Values {
	q := url.Values{}
	if p.After != "" {
		q.Set("after", p.After)
	}
	if p.Limit != nil {
		q.Set("limit", strconv.FormatInt(*p.Limit, 10))
	}
	q.Set("order", string(p.Order))
	return q
}

// encodeHeaders converts the header parameters in p to HTTP request headers.
func (p *GetChatCompletionMessagesParams) encodeHeaders() http.Header {
	h := http.Header{}
	return h
}

// ListContainersParams holds query and header parameters for the ListContainers operation.
type ListContainersParams struct {
	Limit *int64                    `form:"limit"`
	Order ListContainersParamsOrder `form:"order"`
	After string                    `form:"after"`
	Name  string                    `form:"name"`
}

// encode converts the query parameters in p to URL query values.
func (p *ListContainersParams) encode() url.Values {
	q := url.Values{}
	if p.Limit != nil {
		q.Set("limit", strconv.FormatInt(*p.Limit, 10))
	}
	q.Set("order", string(p.Order))
	if p.After != "" {
		q.Set("after", p.After)
	}
	if p.Name != "" {
		q.Set("name", p.Name)
	}
	return q
}

// encodeHeaders converts the header parameters in p to HTTP request headers.
func (p *ListContainersParams) encodeHeaders() http.Header {
	h := http.Header{}
	return h
}

// ListContainerFilesParams holds query and header parameters for the ListContainerFiles operation.
type ListContainerFilesParams struct {
	Limit *int64                        `form:"limit"`
	Order ListContainerFilesParamsOrder `form:"order"`
	After string                        `form:"after"`
}

// encode converts the query parameters in p to URL query values.
func (p *ListContainerFilesParams) encode() url.Values {
	q := url.Values{}
	if p.Limit != nil {
		q.Set("limit", strconv.FormatInt(*p.Limit, 10))
	}
	q.Set("order", string(p.Order))
	if p.After != "" {
		q.Set("after", p.After)
	}
	return q
}

// encodeHeaders converts the header parameters in p to HTTP request headers.
func (p *ListContainerFilesParams) encodeHeaders() http.Header {
	h := http.Header{}
	return h
}

// ListConversationItemsParams holds query and header parameters for the ListConversationItems operation.
type ListConversationItemsParams struct {
	Limit *int64                           `form:"limit"`
	Order ListConversationItemsParamsOrder `form:"order"`
	After string                           `form:"after"`
}

// encode converts the query parameters in p to URL query values.
func (p *ListConversationItemsParams) encode() url.Values {
	q := url.Values{}
	if p.Limit != nil {
		q.Set("limit", strconv.FormatInt(*p.Limit, 10))
	}
	q.Set("order", string(p.Order))
	if p.After != "" {
		q.Set("after", p.After)
	}
	return q
}

// encodeHeaders converts the header parameters in p to HTTP request headers.
func (p *ListConversationItemsParams) encodeHeaders() http.Header {
	h := http.Header{}
	return h
}

// CreateConversationItemsParams holds query and header parameters for the CreateConversationItems operation.
type CreateConversationItemsParams struct {
}

// encode converts the query parameters in p to URL query values.
func (p *CreateConversationItemsParams) encode() url.Values {
	q := url.Values{}
	return q
}

// encodeHeaders converts the header parameters in p to HTTP request headers.
func (p *CreateConversationItemsParams) encodeHeaders() http.Header {
	h := http.Header{}
	return h
}

// GetConversationItemParams holds query and header parameters for the GetConversationItem operation.
type GetConversationItemParams struct {
}

// encode converts the query parameters in p to URL query values.
func (p *GetConversationItemParams) encode() url.Values {
	q := url.Values{}
	return q
}

// encodeHeaders converts the header parameters in p to HTTP request headers.
func (p *GetConversationItemParams) encodeHeaders() http.Header {
	h := http.Header{}
	return h
}

// ListEvalsParams holds query and header parameters for the ListEvals operation.
type ListEvalsParams struct {
	After   string                 `form:"after"`
	Limit   *int64                 `form:"limit"`
	Order   ListEvalsParamsOrder   `form:"order"`
	OrderBy ListEvalsParamsOrderBy `form:"order_by"`
}

// encode converts the query parameters in p to URL query values.
func (p *ListEvalsParams) encode() url.Values {
	q := url.Values{}
	if p.After != "" {
		q.Set("after", p.After)
	}
	if p.Limit != nil {
		q.Set("limit", strconv.FormatInt(*p.Limit, 10))
	}
	q.Set("order", string(p.Order))
	q.Set("order_by", string(p.OrderBy))
	return q
}

// encodeHeaders converts the header parameters in p to HTTP request headers.
func (p *ListEvalsParams) encodeHeaders() http.Header {
	h := http.Header{}
	return h
}

// GetEvalRunsParams holds query and header parameters for the GetEvalRuns operation.
type GetEvalRunsParams struct {
	After  string                  `form:"after"`
	Limit  *int64                  `form:"limit"`
	Order  GetEvalRunsParamsOrder  `form:"order"`
	Status GetEvalRunsParamsStatus `form:"status"`
}

// encode converts the query parameters in p to URL query values.
func (p *GetEvalRunsParams) encode() url.Values {
	q := url.Values{}
	if p.After != "" {
		q.Set("after", p.After)
	}
	if p.Limit != nil {
		q.Set("limit", strconv.FormatInt(*p.Limit, 10))
	}
	q.Set("order", string(p.Order))
	q.Set("status", string(p.Status))
	return q
}

// encodeHeaders converts the header parameters in p to HTTP request headers.
func (p *GetEvalRunsParams) encodeHeaders() http.Header {
	h := http.Header{}
	return h
}

// GetEvalRunOutputItemsParams holds query and header parameters for the GetEvalRunOutputItems operation.
type GetEvalRunOutputItemsParams struct {
	After  string                            `form:"after"`
	Limit  *int64                            `form:"limit"`
	Status GetEvalRunOutputItemsParamsStatus `form:"status"`
	Order  GetEvalRunOutputItemsParamsOrder  `form:"order"`
}

// encode converts the query parameters in p to URL query values.
func (p *GetEvalRunOutputItemsParams) encode() url.Values {
	q := url.Values{}
	if p.After != "" {
		q.Set("after", p.After)
	}
	if p.Limit != nil {
		q.Set("limit", strconv.FormatInt(*p.Limit, 10))
	}
	q.Set("status", string(p.Status))
	q.Set("order", string(p.Order))
	return q
}

// encodeHeaders converts the header parameters in p to HTTP request headers.
func (p *GetEvalRunOutputItemsParams) encodeHeaders() http.Header {
	h := http.Header{}
	return h
}

// ListFilesParams holds query and header parameters for the ListFiles operation.
type ListFilesParams struct {
	Purpose string               `form:"purpose"`
	Limit   *int64               `form:"limit"`
	Order   ListFilesParamsOrder `form:"order"`
	After   string               `form:"after"`
}

// encode converts the query parameters in p to URL query values.
func (p *ListFilesParams) encode() url.Values {
	q := url.Values{}
	if p.Purpose != "" {
		q.Set("purpose", p.Purpose)
	}
	if p.Limit != nil {
		q.Set("limit", strconv.FormatInt(*p.Limit, 10))
	}
	q.Set("order", string(p.Order))
	if p.After != "" {
		q.Set("after", p.After)
	}
	return q
}

// encodeHeaders converts the header parameters in p to HTTP request headers.
func (p *ListFilesParams) encodeHeaders() http.Header {
	h := http.Header{}
	return h
}

// ListFineTuningCheckpointPermissionsParams holds query and header parameters for the ListFineTuningCheckpointPermissions operation.
type ListFineTuningCheckpointPermissionsParams struct {
	ProjectID string                                         `form:"project_id"`
	After     string                                         `form:"after"`
	Limit     *int64                                         `form:"limit"`
	Order     ListFineTuningCheckpointPermissionsParamsOrder `form:"order"`
}

// encode converts the query parameters in p to URL query values.
func (p *ListFineTuningCheckpointPermissionsParams) encode() url.Values {
	q := url.Values{}
	if p.ProjectID != "" {
		q.Set("project_id", p.ProjectID)
	}
	if p.After != "" {
		q.Set("after", p.After)
	}
	if p.Limit != nil {
		q.Set("limit", strconv.FormatInt(*p.Limit, 10))
	}
	q.Set("order", string(p.Order))
	return q
}

// encodeHeaders converts the header parameters in p to HTTP request headers.
func (p *ListFineTuningCheckpointPermissionsParams) encodeHeaders() http.Header {
	h := http.Header{}
	return h
}

// ListPaginatedFineTuningJobsParams holds query and header parameters for the ListPaginatedFineTuningJobs operation.
type ListPaginatedFineTuningJobsParams struct {
	After string `form:"after"`
	Limit *int64 `form:"limit"`
}

// encode converts the query parameters in p to URL query values.
func (p *ListPaginatedFineTuningJobsParams) encode() url.Values {
	q := url.Values{}
	if p.After != "" {
		q.Set("after", p.After)
	}
	if p.Limit != nil {
		q.Set("limit", strconv.FormatInt(*p.Limit, 10))
	}
	return q
}

// encodeHeaders converts the header parameters in p to HTTP request headers.
func (p *ListPaginatedFineTuningJobsParams) encodeHeaders() http.Header {
	h := http.Header{}
	return h
}

// ListFineTuningJobCheckpointsParams holds query and header parameters for the ListFineTuningJobCheckpoints operation.
type ListFineTuningJobCheckpointsParams struct {
	After string `form:"after"`
	Limit *int64 `form:"limit"`
}

// encode converts the query parameters in p to URL query values.
func (p *ListFineTuningJobCheckpointsParams) encode() url.Values {
	q := url.Values{}
	if p.After != "" {
		q.Set("after", p.After)
	}
	if p.Limit != nil {
		q.Set("limit", strconv.FormatInt(*p.Limit, 10))
	}
	return q
}

// encodeHeaders converts the header parameters in p to HTTP request headers.
func (p *ListFineTuningJobCheckpointsParams) encodeHeaders() http.Header {
	h := http.Header{}
	return h
}

// ListFineTuningEventsParams holds query and header parameters for the ListFineTuningEvents operation.
type ListFineTuningEventsParams struct {
	After string `form:"after"`
	Limit *int64 `form:"limit"`
}

// encode converts the query parameters in p to URL query values.
func (p *ListFineTuningEventsParams) encode() url.Values {
	q := url.Values{}
	if p.After != "" {
		q.Set("after", p.After)
	}
	if p.Limit != nil {
		q.Set("limit", strconv.FormatInt(*p.Limit, 10))
	}
	return q
}

// encodeHeaders converts the header parameters in p to HTTP request headers.
func (p *ListFineTuningEventsParams) encodeHeaders() http.Header {
	h := http.Header{}
	return h
}

// AdminAPIKeysListParams holds query and header parameters for the AdminAPIKeysList operation.
type AdminAPIKeysListParams struct {
	After string                      `form:"after"`
	Order AdminAPIKeysListParamsOrder `form:"order"`
	Limit *int64                      `form:"limit"`
}

// encode converts the query parameters in p to URL query values.
func (p *AdminAPIKeysListParams) encode() url.Values {
	q := url.Values{}
	if p.After != "" {
		q.Set("after", p.After)
	}
	q.Set("order", string(p.Order))
	if p.Limit != nil {
		q.Set("limit", strconv.FormatInt(*p.Limit, 10))
	}
	return q
}

// encodeHeaders converts the header parameters in p to HTTP request headers.
func (p *AdminAPIKeysListParams) encodeHeaders() http.Header {
	h := http.Header{}
	return h
}

// ListAuditLogsParams holds query and header parameters for the ListAuditLogs operation.
type ListAuditLogsParams struct {
	ProjectIds  []string `form:"project_ids[]"`
	ActorIds    []string `form:"actor_ids[]"`
	ActorEmails []string `form:"actor_emails[]"`
	ResourceIds []string `form:"resource_ids[]"`
	Limit       *int64   `form:"limit"`
	After       string   `form:"after"`
	Before      string   `form:"before"`
}

// encode converts the query parameters in p to URL query values.
func (p *ListAuditLogsParams) encode() url.Values {
	q := url.Values{}
	for _, v := range p.ProjectIds {
		q.Add("project_ids[]", v)
	}
	for _, v := range p.ActorIds {
		q.Add("actor_ids[]", v)
	}
	for _, v := range p.ActorEmails {
		q.Add("actor_emails[]", v)
	}
	for _, v := range p.ResourceIds {
		q.Add("resource_ids[]", v)
	}
	if p.Limit != nil {
		q.Set("limit", strconv.FormatInt(*p.Limit, 10))
	}
	if p.After != "" {
		q.Set("after", p.After)
	}
	if p.Before != "" {
		q.Set("before", p.Before)
	}
	return q
}

// encodeHeaders converts the header parameters in p to HTTP request headers.
func (p *ListAuditLogsParams) encodeHeaders() http.Header {
	h := http.Header{}
	return h
}

// ListOrganizationCertificatesParams holds query and header parameters for the ListOrganizationCertificates operation.
type ListOrganizationCertificatesParams struct {
	Limit *int64                                  `form:"limit"`
	After string                                  `form:"after"`
	Order ListOrganizationCertificatesParamsOrder `form:"order"`
}

// encode converts the query parameters in p to URL query values.
func (p *ListOrganizationCertificatesParams) encode() url.Values {
	q := url.Values{}
	if p.Limit != nil {
		q.Set("limit", strconv.FormatInt(*p.Limit, 10))
	}
	if p.After != "" {
		q.Set("after", p.After)
	}
	q.Set("order", string(p.Order))
	return q
}

// encodeHeaders converts the header parameters in p to HTTP request headers.
func (p *ListOrganizationCertificatesParams) encodeHeaders() http.Header {
	h := http.Header{}
	return h
}

// GetCertificateParams holds query and header parameters for the GetCertificate operation.
type GetCertificateParams struct {
}

// encode converts the query parameters in p to URL query values.
func (p *GetCertificateParams) encode() url.Values {
	q := url.Values{}
	return q
}

// encodeHeaders converts the header parameters in p to HTTP request headers.
func (p *GetCertificateParams) encodeHeaders() http.Header {
	h := http.Header{}
	return h
}

// UsageCostsParams holds query and header parameters for the UsageCosts operation.
type UsageCostsParams struct {
	StartTime   int64                       `form:"start_time"`
	EndTime     *int64                      `form:"end_time"`
	BucketWidth UsageCostsParamsBucketWidth `form:"bucket_width"`
	ProjectIds  []string                    `form:"project_ids"`
	APIKeyIds   []string                    `form:"api_key_ids"`
	Limit       *int64                      `form:"limit"`
	Page        string                      `form:"page"`
}

// encode converts the query parameters in p to URL query values.
func (p *UsageCostsParams) encode() url.Values {
	q := url.Values{}
	q.Set("start_time", strconv.FormatInt(p.StartTime, 10))
	if p.EndTime != nil {
		q.Set("end_time", strconv.FormatInt(*p.EndTime, 10))
	}
	q.Set("bucket_width", string(p.BucketWidth))
	for _, v := range p.ProjectIds {
		q.Add("project_ids", v)
	}
	for _, v := range p.APIKeyIds {
		q.Add("api_key_ids", v)
	}
	if p.Limit != nil {
		q.Set("limit", strconv.FormatInt(*p.Limit, 10))
	}
	if p.Page != "" {
		q.Set("page", p.Page)
	}
	return q
}

// encodeHeaders converts the header parameters in p to HTTP request headers.
func (p *UsageCostsParams) encodeHeaders() http.Header {
	h := http.Header{}
	return h
}

// ListGroupsParams holds query and header parameters for the ListGroups operation.
type ListGroupsParams struct {
	Limit *int64                `form:"limit"`
	After string                `form:"after"`
	Order ListGroupsParamsOrder `form:"order"`
}

// encode converts the query parameters in p to URL query values.
func (p *ListGroupsParams) encode() url.Values {
	q := url.Values{}
	if p.Limit != nil {
		q.Set("limit", strconv.FormatInt(*p.Limit, 10))
	}
	if p.After != "" {
		q.Set("after", p.After)
	}
	q.Set("order", string(p.Order))
	return q
}

// encodeHeaders converts the header parameters in p to HTTP request headers.
func (p *ListGroupsParams) encodeHeaders() http.Header {
	h := http.Header{}
	return h
}

// ListGroupRoleAssignmentsParams holds query and header parameters for the ListGroupRoleAssignments operation.
type ListGroupRoleAssignmentsParams struct {
	Limit *int64                              `form:"limit"`
	After string                              `form:"after"`
	Order ListGroupRoleAssignmentsParamsOrder `form:"order"`
}

// encode converts the query parameters in p to URL query values.
func (p *ListGroupRoleAssignmentsParams) encode() url.Values {
	q := url.Values{}
	if p.Limit != nil {
		q.Set("limit", strconv.FormatInt(*p.Limit, 10))
	}
	if p.After != "" {
		q.Set("after", p.After)
	}
	q.Set("order", string(p.Order))
	return q
}

// encodeHeaders converts the header parameters in p to HTTP request headers.
func (p *ListGroupRoleAssignmentsParams) encodeHeaders() http.Header {
	h := http.Header{}
	return h
}

// ListGroupUsersParams holds query and header parameters for the ListGroupUsers operation.
type ListGroupUsersParams struct {
	Limit *int64                    `form:"limit"`
	After string                    `form:"after"`
	Order ListGroupUsersParamsOrder `form:"order"`
}

// encode converts the query parameters in p to URL query values.
func (p *ListGroupUsersParams) encode() url.Values {
	q := url.Values{}
	if p.Limit != nil {
		q.Set("limit", strconv.FormatInt(*p.Limit, 10))
	}
	if p.After != "" {
		q.Set("after", p.After)
	}
	q.Set("order", string(p.Order))
	return q
}

// encodeHeaders converts the header parameters in p to HTTP request headers.
func (p *ListGroupUsersParams) encodeHeaders() http.Header {
	h := http.Header{}
	return h
}

// ListInvitesParams holds query and header parameters for the ListInvites operation.
type ListInvitesParams struct {
	Limit *int64 `form:"limit"`
	After string `form:"after"`
}

// encode converts the query parameters in p to URL query values.
func (p *ListInvitesParams) encode() url.Values {
	q := url.Values{}
	if p.Limit != nil {
		q.Set("limit", strconv.FormatInt(*p.Limit, 10))
	}
	if p.After != "" {
		q.Set("after", p.After)
	}
	return q
}

// encodeHeaders converts the header parameters in p to HTTP request headers.
func (p *ListInvitesParams) encodeHeaders() http.Header {
	h := http.Header{}
	return h
}

// ListProjectsParams holds query and header parameters for the ListProjects operation.
type ListProjectsParams struct {
	Limit           *int64 `form:"limit"`
	After           string `form:"after"`
	IncludeArchived *bool  `form:"include_archived"`
}

// encode converts the query parameters in p to URL query values.
func (p *ListProjectsParams) encode() url.Values {
	q := url.Values{}
	if p.Limit != nil {
		q.Set("limit", strconv.FormatInt(*p.Limit, 10))
	}
	if p.After != "" {
		q.Set("after", p.After)
	}
	if p.IncludeArchived != nil {
		q.Set("include_archived", strconv.FormatBool(*p.IncludeArchived))
	}
	return q
}

// encodeHeaders converts the header parameters in p to HTTP request headers.
func (p *ListProjectsParams) encodeHeaders() http.Header {
	h := http.Header{}
	return h
}

// ListProjectAPIKeysParams holds query and header parameters for the ListProjectAPIKeys operation.
type ListProjectAPIKeysParams struct {
	Limit *int64 `form:"limit"`
	After string `form:"after"`
}

// encode converts the query parameters in p to URL query values.
func (p *ListProjectAPIKeysParams) encode() url.Values {
	q := url.Values{}
	if p.Limit != nil {
		q.Set("limit", strconv.FormatInt(*p.Limit, 10))
	}
	if p.After != "" {
		q.Set("after", p.After)
	}
	return q
}

// encodeHeaders converts the header parameters in p to HTTP request headers.
func (p *ListProjectAPIKeysParams) encodeHeaders() http.Header {
	h := http.Header{}
	return h
}

// ListProjectCertificatesParams holds query and header parameters for the ListProjectCertificates operation.
type ListProjectCertificatesParams struct {
	Limit *int64                             `form:"limit"`
	After string                             `form:"after"`
	Order ListProjectCertificatesParamsOrder `form:"order"`
}

// encode converts the query parameters in p to URL query values.
func (p *ListProjectCertificatesParams) encode() url.Values {
	q := url.Values{}
	if p.Limit != nil {
		q.Set("limit", strconv.FormatInt(*p.Limit, 10))
	}
	if p.After != "" {
		q.Set("after", p.After)
	}
	q.Set("order", string(p.Order))
	return q
}

// encodeHeaders converts the header parameters in p to HTTP request headers.
func (p *ListProjectCertificatesParams) encodeHeaders() http.Header {
	h := http.Header{}
	return h
}

// ListProjectGroupsParams holds query and header parameters for the ListProjectGroups operation.
type ListProjectGroupsParams struct {
	Limit *int64                       `form:"limit"`
	After string                       `form:"after"`
	Order ListProjectGroupsParamsOrder `form:"order"`
}

// encode converts the query parameters in p to URL query values.
func (p *ListProjectGroupsParams) encode() url.Values {
	q := url.Values{}
	if p.Limit != nil {
		q.Set("limit", strconv.FormatInt(*p.Limit, 10))
	}
	if p.After != "" {
		q.Set("after", p.After)
	}
	q.Set("order", string(p.Order))
	return q
}

// encodeHeaders converts the header parameters in p to HTTP request headers.
func (p *ListProjectGroupsParams) encodeHeaders() http.Header {
	h := http.Header{}
	return h
}

// ListProjectRateLimitsParams holds query and header parameters for the ListProjectRateLimits operation.
type ListProjectRateLimitsParams struct {
	Limit  *int64 `form:"limit"`
	After  string `form:"after"`
	Before string `form:"before"`
}

// encode converts the query parameters in p to URL query values.
func (p *ListProjectRateLimitsParams) encode() url.Values {
	q := url.Values{}
	if p.Limit != nil {
		q.Set("limit", strconv.FormatInt(*p.Limit, 10))
	}
	if p.After != "" {
		q.Set("after", p.After)
	}
	if p.Before != "" {
		q.Set("before", p.Before)
	}
	return q
}

// encodeHeaders converts the header parameters in p to HTTP request headers.
func (p *ListProjectRateLimitsParams) encodeHeaders() http.Header {
	h := http.Header{}
	return h
}

// ListProjectServiceAccountsParams holds query and header parameters for the ListProjectServiceAccounts operation.
type ListProjectServiceAccountsParams struct {
	Limit *int64 `form:"limit"`
	After string `form:"after"`
}

// encode converts the query parameters in p to URL query values.
func (p *ListProjectServiceAccountsParams) encode() url.Values {
	q := url.Values{}
	if p.Limit != nil {
		q.Set("limit", strconv.FormatInt(*p.Limit, 10))
	}
	if p.After != "" {
		q.Set("after", p.After)
	}
	return q
}

// encodeHeaders converts the header parameters in p to HTTP request headers.
func (p *ListProjectServiceAccountsParams) encodeHeaders() http.Header {
	h := http.Header{}
	return h
}

// ListProjectUsersParams holds query and header parameters for the ListProjectUsers operation.
type ListProjectUsersParams struct {
	Limit *int64 `form:"limit"`
	After string `form:"after"`
}

// encode converts the query parameters in p to URL query values.
func (p *ListProjectUsersParams) encode() url.Values {
	q := url.Values{}
	if p.Limit != nil {
		q.Set("limit", strconv.FormatInt(*p.Limit, 10))
	}
	if p.After != "" {
		q.Set("after", p.After)
	}
	return q
}

// encodeHeaders converts the header parameters in p to HTTP request headers.
func (p *ListProjectUsersParams) encodeHeaders() http.Header {
	h := http.Header{}
	return h
}

// ListRolesParams holds query and header parameters for the ListRoles operation.
type ListRolesParams struct {
	Limit *int64               `form:"limit"`
	After string               `form:"after"`
	Order ListRolesParamsOrder `form:"order"`
}

// encode converts the query parameters in p to URL query values.
func (p *ListRolesParams) encode() url.Values {
	q := url.Values{}
	if p.Limit != nil {
		q.Set("limit", strconv.FormatInt(*p.Limit, 10))
	}
	if p.After != "" {
		q.Set("after", p.After)
	}
	q.Set("order", string(p.Order))
	return q
}

// encodeHeaders converts the header parameters in p to HTTP request headers.
func (p *ListRolesParams) encodeHeaders() http.Header {
	h := http.Header{}
	return h
}

// UsageAudioSpeechesParams holds query and header parameters for the UsageAudioSpeeches operation.
type UsageAudioSpeechesParams struct {
	StartTime   int64                               `form:"start_time"`
	EndTime     *int64                              `form:"end_time"`
	BucketWidth UsageAudioSpeechesParamsBucketWidth `form:"bucket_width"`
	ProjectIds  []string                            `form:"project_ids"`
	UserIds     []string                            `form:"user_ids"`
	APIKeyIds   []string                            `form:"api_key_ids"`
	Models      []string                            `form:"models"`
	Limit       *int64                              `form:"limit"`
	Page        string                              `form:"page"`
}

// encode converts the query parameters in p to URL query values.
func (p *UsageAudioSpeechesParams) encode() url.Values {
	q := url.Values{}
	q.Set("start_time", strconv.FormatInt(p.StartTime, 10))
	if p.EndTime != nil {
		q.Set("end_time", strconv.FormatInt(*p.EndTime, 10))
	}
	q.Set("bucket_width", string(p.BucketWidth))
	for _, v := range p.ProjectIds {
		q.Add("project_ids", v)
	}
	for _, v := range p.UserIds {
		q.Add("user_ids", v)
	}
	for _, v := range p.APIKeyIds {
		q.Add("api_key_ids", v)
	}
	for _, v := range p.Models {
		q.Add("models", v)
	}
	if p.Limit != nil {
		q.Set("limit", strconv.FormatInt(*p.Limit, 10))
	}
	if p.Page != "" {
		q.Set("page", p.Page)
	}
	return q
}

// encodeHeaders converts the header parameters in p to HTTP request headers.
func (p *UsageAudioSpeechesParams) encodeHeaders() http.Header {
	h := http.Header{}
	return h
}

// UsageAudioTranscriptionsParams holds query and header parameters for the UsageAudioTranscriptions operation.
type UsageAudioTranscriptionsParams struct {
	StartTime   int64                                     `form:"start_time"`
	EndTime     *int64                                    `form:"end_time"`
	BucketWidth UsageAudioTranscriptionsParamsBucketWidth `form:"bucket_width"`
	ProjectIds  []string                                  `form:"project_ids"`
	UserIds     []string                                  `form:"user_ids"`
	APIKeyIds   []string                                  `form:"api_key_ids"`
	Models      []string                                  `form:"models"`
	Limit       *int64                                    `form:"limit"`
	Page        string                                    `form:"page"`
}

// encode converts the query parameters in p to URL query values.
func (p *UsageAudioTranscriptionsParams) encode() url.Values {
	q := url.Values{}
	q.Set("start_time", strconv.FormatInt(p.StartTime, 10))
	if p.EndTime != nil {
		q.Set("end_time", strconv.FormatInt(*p.EndTime, 10))
	}
	q.Set("bucket_width", string(p.BucketWidth))
	for _, v := range p.ProjectIds {
		q.Add("project_ids", v)
	}
	for _, v := range p.UserIds {
		q.Add("user_ids", v)
	}
	for _, v := range p.APIKeyIds {
		q.Add("api_key_ids", v)
	}
	for _, v := range p.Models {
		q.Add("models", v)
	}
	if p.Limit != nil {
		q.Set("limit", strconv.FormatInt(*p.Limit, 10))
	}
	if p.Page != "" {
		q.Set("page", p.Page)
	}
	return q
}

// encodeHeaders converts the header parameters in p to HTTP request headers.
func (p *UsageAudioTranscriptionsParams) encodeHeaders() http.Header {
	h := http.Header{}
	return h
}

// UsageCodeInterpreterSessionsParams holds query and header parameters for the UsageCodeInterpreterSessions operation.
type UsageCodeInterpreterSessionsParams struct {
	StartTime   int64                                         `form:"start_time"`
	EndTime     *int64                                        `form:"end_time"`
	BucketWidth UsageCodeInterpreterSessionsParamsBucketWidth `form:"bucket_width"`
	ProjectIds  []string                                      `form:"project_ids"`
	Limit       *int64                                        `form:"limit"`
	Page        string                                        `form:"page"`
}

// encode converts the query parameters in p to URL query values.
func (p *UsageCodeInterpreterSessionsParams) encode() url.Values {
	q := url.Values{}
	q.Set("start_time", strconv.FormatInt(p.StartTime, 10))
	if p.EndTime != nil {
		q.Set("end_time", strconv.FormatInt(*p.EndTime, 10))
	}
	q.Set("bucket_width", string(p.BucketWidth))
	for _, v := range p.ProjectIds {
		q.Add("project_ids", v)
	}
	if p.Limit != nil {
		q.Set("limit", strconv.FormatInt(*p.Limit, 10))
	}
	if p.Page != "" {
		q.Set("page", p.Page)
	}
	return q
}

// encodeHeaders converts the header parameters in p to HTTP request headers.
func (p *UsageCodeInterpreterSessionsParams) encodeHeaders() http.Header {
	h := http.Header{}
	return h
}

// UsageCompletionsParams holds query and header parameters for the UsageCompletions operation.
type UsageCompletionsParams struct {
	StartTime   int64                             `form:"start_time"`
	EndTime     *int64                            `form:"end_time"`
	BucketWidth UsageCompletionsParamsBucketWidth `form:"bucket_width"`
	ProjectIds  []string                          `form:"project_ids"`
	UserIds     []string                          `form:"user_ids"`
	APIKeyIds   []string                          `form:"api_key_ids"`
	Models      []string                          `form:"models"`
	Batch       *bool                             `form:"batch"`
	Limit       *int64                            `form:"limit"`
	Page        string                            `form:"page"`
}

// encode converts the query parameters in p to URL query values.
func (p *UsageCompletionsParams) encode() url.Values {
	q := url.Values{}
	q.Set("start_time", strconv.FormatInt(p.StartTime, 10))
	if p.EndTime != nil {
		q.Set("end_time", strconv.FormatInt(*p.EndTime, 10))
	}
	q.Set("bucket_width", string(p.BucketWidth))
	for _, v := range p.ProjectIds {
		q.Add("project_ids", v)
	}
	for _, v := range p.UserIds {
		q.Add("user_ids", v)
	}
	for _, v := range p.APIKeyIds {
		q.Add("api_key_ids", v)
	}
	for _, v := range p.Models {
		q.Add("models", v)
	}
	if p.Batch != nil {
		q.Set("batch", strconv.FormatBool(*p.Batch))
	}
	if p.Limit != nil {
		q.Set("limit", strconv.FormatInt(*p.Limit, 10))
	}
	if p.Page != "" {
		q.Set("page", p.Page)
	}
	return q
}

// encodeHeaders converts the header parameters in p to HTTP request headers.
func (p *UsageCompletionsParams) encodeHeaders() http.Header {
	h := http.Header{}
	return h
}

// UsageEmbeddingsParams holds query and header parameters for the UsageEmbeddings operation.
type UsageEmbeddingsParams struct {
	StartTime   int64                            `form:"start_time"`
	EndTime     *int64                           `form:"end_time"`
	BucketWidth UsageEmbeddingsParamsBucketWidth `form:"bucket_width"`
	ProjectIds  []string                         `form:"project_ids"`
	UserIds     []string                         `form:"user_ids"`
	APIKeyIds   []string                         `form:"api_key_ids"`
	Models      []string                         `form:"models"`
	Limit       *int64                           `form:"limit"`
	Page        string                           `form:"page"`
}

// encode converts the query parameters in p to URL query values.
func (p *UsageEmbeddingsParams) encode() url.Values {
	q := url.Values{}
	q.Set("start_time", strconv.FormatInt(p.StartTime, 10))
	if p.EndTime != nil {
		q.Set("end_time", strconv.FormatInt(*p.EndTime, 10))
	}
	q.Set("bucket_width", string(p.BucketWidth))
	for _, v := range p.ProjectIds {
		q.Add("project_ids", v)
	}
	for _, v := range p.UserIds {
		q.Add("user_ids", v)
	}
	for _, v := range p.APIKeyIds {
		q.Add("api_key_ids", v)
	}
	for _, v := range p.Models {
		q.Add("models", v)
	}
	if p.Limit != nil {
		q.Set("limit", strconv.FormatInt(*p.Limit, 10))
	}
	if p.Page != "" {
		q.Set("page", p.Page)
	}
	return q
}

// encodeHeaders converts the header parameters in p to HTTP request headers.
func (p *UsageEmbeddingsParams) encodeHeaders() http.Header {
	h := http.Header{}
	return h
}

// UsageImagesParams holds query and header parameters for the UsageImages operation.
type UsageImagesParams struct {
	StartTime   int64                        `form:"start_time"`
	EndTime     *int64                       `form:"end_time"`
	BucketWidth UsageImagesParamsBucketWidth `form:"bucket_width"`
	ProjectIds  []string                     `form:"project_ids"`
	UserIds     []string                     `form:"user_ids"`
	APIKeyIds   []string                     `form:"api_key_ids"`
	Models      []string                     `form:"models"`
	Limit       *int64                       `form:"limit"`
	Page        string                       `form:"page"`
}

// encode converts the query parameters in p to URL query values.
func (p *UsageImagesParams) encode() url.Values {
	q := url.Values{}
	q.Set("start_time", strconv.FormatInt(p.StartTime, 10))
	if p.EndTime != nil {
		q.Set("end_time", strconv.FormatInt(*p.EndTime, 10))
	}
	q.Set("bucket_width", string(p.BucketWidth))
	for _, v := range p.ProjectIds {
		q.Add("project_ids", v)
	}
	for _, v := range p.UserIds {
		q.Add("user_ids", v)
	}
	for _, v := range p.APIKeyIds {
		q.Add("api_key_ids", v)
	}
	for _, v := range p.Models {
		q.Add("models", v)
	}
	if p.Limit != nil {
		q.Set("limit", strconv.FormatInt(*p.Limit, 10))
	}
	if p.Page != "" {
		q.Set("page", p.Page)
	}
	return q
}

// encodeHeaders converts the header parameters in p to HTTP request headers.
func (p *UsageImagesParams) encodeHeaders() http.Header {
	h := http.Header{}
	return h
}

// UsageModerationsParams holds query and header parameters for the UsageModerations operation.
type UsageModerationsParams struct {
	StartTime   int64                             `form:"start_time"`
	EndTime     *int64                            `form:"end_time"`
	BucketWidth UsageModerationsParamsBucketWidth `form:"bucket_width"`
	ProjectIds  []string                          `form:"project_ids"`
	UserIds     []string                          `form:"user_ids"`
	APIKeyIds   []string                          `form:"api_key_ids"`
	Models      []string                          `form:"models"`
	Limit       *int64                            `form:"limit"`
	Page        string                            `form:"page"`
}

// encode converts the query parameters in p to URL query values.
func (p *UsageModerationsParams) encode() url.Values {
	q := url.Values{}
	q.Set("start_time", strconv.FormatInt(p.StartTime, 10))
	if p.EndTime != nil {
		q.Set("end_time", strconv.FormatInt(*p.EndTime, 10))
	}
	q.Set("bucket_width", string(p.BucketWidth))
	for _, v := range p.ProjectIds {
		q.Add("project_ids", v)
	}
	for _, v := range p.UserIds {
		q.Add("user_ids", v)
	}
	for _, v := range p.APIKeyIds {
		q.Add("api_key_ids", v)
	}
	for _, v := range p.Models {
		q.Add("models", v)
	}
	if p.Limit != nil {
		q.Set("limit", strconv.FormatInt(*p.Limit, 10))
	}
	if p.Page != "" {
		q.Set("page", p.Page)
	}
	return q
}

// encodeHeaders converts the header parameters in p to HTTP request headers.
func (p *UsageModerationsParams) encodeHeaders() http.Header {
	h := http.Header{}
	return h
}

// UsageVectorStoresParams holds query and header parameters for the UsageVectorStores operation.
type UsageVectorStoresParams struct {
	StartTime   int64                              `form:"start_time"`
	EndTime     *int64                             `form:"end_time"`
	BucketWidth UsageVectorStoresParamsBucketWidth `form:"bucket_width"`
	ProjectIds  []string                           `form:"project_ids"`
	Limit       *int64                             `form:"limit"`
	Page        string                             `form:"page"`
}

// encode converts the query parameters in p to URL query values.
func (p *UsageVectorStoresParams) encode() url.Values {
	q := url.Values{}
	q.Set("start_time", strconv.FormatInt(p.StartTime, 10))
	if p.EndTime != nil {
		q.Set("end_time", strconv.FormatInt(*p.EndTime, 10))
	}
	q.Set("bucket_width", string(p.BucketWidth))
	for _, v := range p.ProjectIds {
		q.Add("project_ids", v)
	}
	if p.Limit != nil {
		q.Set("limit", strconv.FormatInt(*p.Limit, 10))
	}
	if p.Page != "" {
		q.Set("page", p.Page)
	}
	return q
}

// encodeHeaders converts the header parameters in p to HTTP request headers.
func (p *UsageVectorStoresParams) encodeHeaders() http.Header {
	h := http.Header{}
	return h
}

// ListUsersParams holds query and header parameters for the ListUsers operation.
type ListUsersParams struct {
	Limit  *int64   `form:"limit"`
	After  string   `form:"after"`
	Emails []string `form:"emails"`
}

// encode converts the query parameters in p to URL query values.
func (p *ListUsersParams) encode() url.Values {
	q := url.Values{}
	if p.Limit != nil {
		q.Set("limit", strconv.FormatInt(*p.Limit, 10))
	}
	if p.After != "" {
		q.Set("after", p.After)
	}
	for _, v := range p.Emails {
		q.Add("emails", v)
	}
	return q
}

// encodeHeaders converts the header parameters in p to HTTP request headers.
func (p *ListUsersParams) encodeHeaders() http.Header {
	h := http.Header{}
	return h
}

// ListUserRoleAssignmentsParams holds query and header parameters for the ListUserRoleAssignments operation.
type ListUserRoleAssignmentsParams struct {
	Limit *int64                             `form:"limit"`
	After string                             `form:"after"`
	Order ListUserRoleAssignmentsParamsOrder `form:"order"`
}

// encode converts the query parameters in p to URL query values.
func (p *ListUserRoleAssignmentsParams) encode() url.Values {
	q := url.Values{}
	if p.Limit != nil {
		q.Set("limit", strconv.FormatInt(*p.Limit, 10))
	}
	if p.After != "" {
		q.Set("after", p.After)
	}
	q.Set("order", string(p.Order))
	return q
}

// encodeHeaders converts the header parameters in p to HTTP request headers.
func (p *ListUserRoleAssignmentsParams) encodeHeaders() http.Header {
	h := http.Header{}
	return h
}

// ListProjectGroupRoleAssignmentsParams holds query and header parameters for the ListProjectGroupRoleAssignments operation.
type ListProjectGroupRoleAssignmentsParams struct {
	Limit *int64                                     `form:"limit"`
	After string                                     `form:"after"`
	Order ListProjectGroupRoleAssignmentsParamsOrder `form:"order"`
}

// encode converts the query parameters in p to URL query values.
func (p *ListProjectGroupRoleAssignmentsParams) encode() url.Values {
	q := url.Values{}
	if p.Limit != nil {
		q.Set("limit", strconv.FormatInt(*p.Limit, 10))
	}
	if p.After != "" {
		q.Set("after", p.After)
	}
	q.Set("order", string(p.Order))
	return q
}

// encodeHeaders converts the header parameters in p to HTTP request headers.
func (p *ListProjectGroupRoleAssignmentsParams) encodeHeaders() http.Header {
	h := http.Header{}
	return h
}

// ListProjectRolesParams holds query and header parameters for the ListProjectRoles operation.
type ListProjectRolesParams struct {
	Limit *int64                      `form:"limit"`
	After string                      `form:"after"`
	Order ListProjectRolesParamsOrder `form:"order"`
}

// encode converts the query parameters in p to URL query values.
func (p *ListProjectRolesParams) encode() url.Values {
	q := url.Values{}
	if p.Limit != nil {
		q.Set("limit", strconv.FormatInt(*p.Limit, 10))
	}
	if p.After != "" {
		q.Set("after", p.After)
	}
	q.Set("order", string(p.Order))
	return q
}

// encodeHeaders converts the header parameters in p to HTTP request headers.
func (p *ListProjectRolesParams) encodeHeaders() http.Header {
	h := http.Header{}
	return h
}

// ListProjectUserRoleAssignmentsParams holds query and header parameters for the ListProjectUserRoleAssignments operation.
type ListProjectUserRoleAssignmentsParams struct {
	Limit *int64                                    `form:"limit"`
	After string                                    `form:"after"`
	Order ListProjectUserRoleAssignmentsParamsOrder `form:"order"`
}

// encode converts the query parameters in p to URL query values.
func (p *ListProjectUserRoleAssignmentsParams) encode() url.Values {
	q := url.Values{}
	if p.Limit != nil {
		q.Set("limit", strconv.FormatInt(*p.Limit, 10))
	}
	if p.After != "" {
		q.Set("after", p.After)
	}
	q.Set("order", string(p.Order))
	return q
}

// encodeHeaders converts the header parameters in p to HTTP request headers.
func (p *ListProjectUserRoleAssignmentsParams) encodeHeaders() http.Header {
	h := http.Header{}
	return h
}

// GetResponseParams holds query and header parameters for the GetResponse operation.
type GetResponseParams struct {
	Stream             *bool  `form:"stream"`
	StartingAfter      *int64 `form:"starting_after"`
	IncludeObfuscation *bool  `form:"include_obfuscation"`
}

// encode converts the query parameters in p to URL query values.
func (p *GetResponseParams) encode() url.Values {
	q := url.Values{}
	if p.Stream != nil {
		q.Set("stream", strconv.FormatBool(*p.Stream))
	}
	if p.StartingAfter != nil {
		q.Set("starting_after", strconv.FormatInt(*p.StartingAfter, 10))
	}
	if p.IncludeObfuscation != nil {
		q.Set("include_obfuscation", strconv.FormatBool(*p.IncludeObfuscation))
	}
	return q
}

// encodeHeaders converts the header parameters in p to HTTP request headers.
func (p *GetResponseParams) encodeHeaders() http.Header {
	h := http.Header{}
	return h
}

// ListInputItemsParams holds query and header parameters for the ListInputItems operation.
type ListInputItemsParams struct {
	Limit *int64                    `form:"limit"`
	Order ListInputItemsParamsOrder `form:"order"`
	After string                    `form:"after"`
}

// encode converts the query parameters in p to URL query values.
func (p *ListInputItemsParams) encode() url.Values {
	q := url.Values{}
	if p.Limit != nil {
		q.Set("limit", strconv.FormatInt(*p.Limit, 10))
	}
	q.Set("order", string(p.Order))
	if p.After != "" {
		q.Set("after", p.After)
	}
	return q
}

// encodeHeaders converts the header parameters in p to HTTP request headers.
func (p *ListInputItemsParams) encodeHeaders() http.Header {
	h := http.Header{}
	return h
}

// ListMessagesParams holds query and header parameters for the ListMessages operation.
type ListMessagesParams struct {
	Limit  *int64                  `form:"limit"`
	Order  ListMessagesParamsOrder `form:"order"`
	After  string                  `form:"after"`
	Before string                  `form:"before"`
	RunID  string                  `form:"run_id"`
}

// encode converts the query parameters in p to URL query values.
func (p *ListMessagesParams) encode() url.Values {
	q := url.Values{}
	if p.Limit != nil {
		q.Set("limit", strconv.FormatInt(*p.Limit, 10))
	}
	q.Set("order", string(p.Order))
	if p.After != "" {
		q.Set("after", p.After)
	}
	if p.Before != "" {
		q.Set("before", p.Before)
	}
	if p.RunID != "" {
		q.Set("run_id", p.RunID)
	}
	return q
}

// encodeHeaders converts the header parameters in p to HTTP request headers.
func (p *ListMessagesParams) encodeHeaders() http.Header {
	h := http.Header{}
	return h
}

// ListRunsParams holds query and header parameters for the ListRuns operation.
type ListRunsParams struct {
	Limit  *int64              `form:"limit"`
	Order  ListRunsParamsOrder `form:"order"`
	After  string              `form:"after"`
	Before string              `form:"before"`
}

// encode converts the query parameters in p to URL query values.
func (p *ListRunsParams) encode() url.Values {
	q := url.Values{}
	if p.Limit != nil {
		q.Set("limit", strconv.FormatInt(*p.Limit, 10))
	}
	q.Set("order", string(p.Order))
	if p.After != "" {
		q.Set("after", p.After)
	}
	if p.Before != "" {
		q.Set("before", p.Before)
	}
	return q
}

// encodeHeaders converts the header parameters in p to HTTP request headers.
func (p *ListRunsParams) encodeHeaders() http.Header {
	h := http.Header{}
	return h
}

// CreateRunParams holds query and header parameters for the CreateRun operation.
type CreateRunParams struct {
}

// encode converts the query parameters in p to URL query values.
func (p *CreateRunParams) encode() url.Values {
	q := url.Values{}
	return q
}

// encodeHeaders converts the header parameters in p to HTTP request headers.
func (p *CreateRunParams) encodeHeaders() http.Header {
	h := http.Header{}
	return h
}

// ListRunStepsParams holds query and header parameters for the ListRunSteps operation.
type ListRunStepsParams struct {
	Limit  *int64                  `form:"limit"`
	Order  ListRunStepsParamsOrder `form:"order"`
	After  string                  `form:"after"`
	Before string                  `form:"before"`
}

// encode converts the query parameters in p to URL query values.
func (p *ListRunStepsParams) encode() url.Values {
	q := url.Values{}
	if p.Limit != nil {
		q.Set("limit", strconv.FormatInt(*p.Limit, 10))
	}
	q.Set("order", string(p.Order))
	if p.After != "" {
		q.Set("after", p.After)
	}
	if p.Before != "" {
		q.Set("before", p.Before)
	}
	return q
}

// encodeHeaders converts the header parameters in p to HTTP request headers.
func (p *ListRunStepsParams) encodeHeaders() http.Header {
	h := http.Header{}
	return h
}

// GetRunStepParams holds query and header parameters for the GetRunStep operation.
type GetRunStepParams struct {
}

// encode converts the query parameters in p to URL query values.
func (p *GetRunStepParams) encode() url.Values {
	q := url.Values{}
	return q
}

// encodeHeaders converts the header parameters in p to HTTP request headers.
func (p *GetRunStepParams) encodeHeaders() http.Header {
	h := http.Header{}
	return h
}

// ListVectorStoresParams holds query and header parameters for the ListVectorStores operation.
type ListVectorStoresParams struct {
	Limit  *int64                      `form:"limit"`
	Order  ListVectorStoresParamsOrder `form:"order"`
	After  string                      `form:"after"`
	Before string                      `form:"before"`
}

// encode converts the query parameters in p to URL query values.
func (p *ListVectorStoresParams) encode() url.Values {
	q := url.Values{}
	if p.Limit != nil {
		q.Set("limit", strconv.FormatInt(*p.Limit, 10))
	}
	q.Set("order", string(p.Order))
	if p.After != "" {
		q.Set("after", p.After)
	}
	if p.Before != "" {
		q.Set("before", p.Before)
	}
	return q
}

// encodeHeaders converts the header parameters in p to HTTP request headers.
func (p *ListVectorStoresParams) encodeHeaders() http.Header {
	h := http.Header{}
	return h
}

// ListFilesInVectorStoreBatchParams holds query and header parameters for the ListFilesInVectorStoreBatch operation.
type ListFilesInVectorStoreBatchParams struct {
	Limit  *int64                                  `form:"limit"`
	Order  ListFilesInVectorStoreBatchParamsOrder  `form:"order"`
	After  string                                  `form:"after"`
	Before string                                  `form:"before"`
	Filter ListFilesInVectorStoreBatchParamsFilter `form:"filter"`
}

// encode converts the query parameters in p to URL query values.
func (p *ListFilesInVectorStoreBatchParams) encode() url.Values {
	q := url.Values{}
	if p.Limit != nil {
		q.Set("limit", strconv.FormatInt(*p.Limit, 10))
	}
	q.Set("order", string(p.Order))
	if p.After != "" {
		q.Set("after", p.After)
	}
	if p.Before != "" {
		q.Set("before", p.Before)
	}
	q.Set("filter", string(p.Filter))
	return q
}

// encodeHeaders converts the header parameters in p to HTTP request headers.
func (p *ListFilesInVectorStoreBatchParams) encodeHeaders() http.Header {
	h := http.Header{}
	return h
}

// ListVectorStoreFilesParams holds query and header parameters for the ListVectorStoreFiles operation.
type ListVectorStoreFilesParams struct {
	Limit  *int64                           `form:"limit"`
	Order  ListVectorStoreFilesParamsOrder  `form:"order"`
	After  string                           `form:"after"`
	Before string                           `form:"before"`
	Filter ListVectorStoreFilesParamsFilter `form:"filter"`
}

// encode converts the query parameters in p to URL query values.
func (p *ListVectorStoreFilesParams) encode() url.Values {
	q := url.Values{}
	if p.Limit != nil {
		q.Set("limit", strconv.FormatInt(*p.Limit, 10))
	}
	q.Set("order", string(p.Order))
	if p.After != "" {
		q.Set("after", p.After)
	}
	if p.Before != "" {
		q.Set("before", p.Before)
	}
	q.Set("filter", string(p.Filter))
	return q
}

// encodeHeaders converts the header parameters in p to HTTP request headers.
func (p *ListVectorStoreFilesParams) encodeHeaders() http.Header {
	h := http.Header{}
	return h
}

// ListVideosParams holds query and header parameters for the ListVideos operation.
type ListVideosParams struct {
	Limit *int64    `form:"limit"`
	Order OrderEnum `form:"order"`
	After string    `form:"after"`
}

// encode converts the query parameters in p to URL query values.
func (p *ListVideosParams) encode() url.Values {
	q := url.Values{}
	if p.Limit != nil {
		q.Set("limit", strconv.FormatInt(*p.Limit, 10))
	}
	q.Set("order", string(p.Order))
	if p.After != "" {
		q.Set("after", p.After)
	}
	return q
}

// encodeHeaders converts the header parameters in p to HTTP request headers.
func (p *ListVideosParams) encodeHeaders() http.Header {
	h := http.Header{}
	return h
}

// RetrieveVideoContentParams holds query and header parameters for the RetrieveVideoContent operation.
type RetrieveVideoContentParams struct {
	Variant VideoContentVariant `form:"variant"`
}

// encode converts the query parameters in p to URL query values.
func (p *RetrieveVideoContentParams) encode() url.Values {
	q := url.Values{}
	q.Set("variant", string(p.Variant))
	return q
}

// encodeHeaders converts the header parameters in p to HTTP request headers.
func (p *RetrieveVideoContentParams) encodeHeaders() http.Header {
	h := http.Header{}
	return h
}

// ListSkillsParams holds query and header parameters for the ListSkills operation.
type ListSkillsParams struct {
	Limit *int64    `form:"limit"`
	Order OrderEnum `form:"order"`
	After string    `form:"after"`
}

// encode converts the query parameters in p to URL query values.
func (p *ListSkillsParams) encode() url.Values {
	q := url.Values{}
	if p.Limit != nil {
		q.Set("limit", strconv.FormatInt(*p.Limit, 10))
	}
	q.Set("order", string(p.Order))
	if p.After != "" {
		q.Set("after", p.After)
	}
	return q
}

// encodeHeaders converts the header parameters in p to HTTP request headers.
func (p *ListSkillsParams) encodeHeaders() http.Header {
	h := http.Header{}
	return h
}

// ListSkillVersionsParams holds query and header parameters for the ListSkillVersions operation.
type ListSkillVersionsParams struct {
	Limit *int64    `form:"limit"`
	Order OrderEnum `form:"order"`
	After string    `form:"after"`
}

// encode converts the query parameters in p to URL query values.
func (p *ListSkillVersionsParams) encode() url.Values {
	q := url.Values{}
	if p.Limit != nil {
		q.Set("limit", strconv.FormatInt(*p.Limit, 10))
	}
	q.Set("order", string(p.Order))
	if p.After != "" {
		q.Set("after", p.After)
	}
	return q
}

// encodeHeaders converts the header parameters in p to HTTP request headers.
func (p *ListSkillVersionsParams) encodeHeaders() http.Header {
	h := http.Header{}
	return h
}

// ListThreadItemsMethodParams holds query and header parameters for the ListThreadItemsMethod operation.
type ListThreadItemsMethodParams struct {
	Limit  *int64    `form:"limit"`
	Order  OrderEnum `form:"order"`
	After  string    `form:"after"`
	Before string    `form:"before"`
}

// encode converts the query parameters in p to URL query values.
func (p *ListThreadItemsMethodParams) encode() url.Values {
	q := url.Values{}
	if p.Limit != nil {
		q.Set("limit", strconv.FormatInt(*p.Limit, 10))
	}
	q.Set("order", string(p.Order))
	if p.After != "" {
		q.Set("after", p.After)
	}
	if p.Before != "" {
		q.Set("before", p.Before)
	}
	return q
}

// encodeHeaders converts the header parameters in p to HTTP request headers.
func (p *ListThreadItemsMethodParams) encodeHeaders() http.Header {
	h := http.Header{}
	return h
}

// ListThreadsMethodParams holds query and header parameters for the ListThreadsMethod operation.
type ListThreadsMethodParams struct {
	Limit  *int64    `form:"limit"`
	Order  OrderEnum `form:"order"`
	After  string    `form:"after"`
	Before string    `form:"before"`
	User   string    `form:"user"`
}

// encode converts the query parameters in p to URL query values.
func (p *ListThreadsMethodParams) encode() url.Values {
	q := url.Values{}
	if p.Limit != nil {
		q.Set("limit", strconv.FormatInt(*p.Limit, 10))
	}
	q.Set("order", string(p.Order))
	if p.After != "" {
		q.Set("after", p.After)
	}
	if p.Before != "" {
		q.Set("before", p.Before)
	}
	if p.User != "" {
		q.Set("user", p.User)
	}
	return q
}

// encodeHeaders converts the header parameters in p to HTTP request headers.
func (p *ListThreadsMethodParams) encodeHeaders() http.Header {
	h := http.Header{}
	return h
}
